export const GLUTENS = [
	'all-purpose flour',
	'bulgur',
	'burger bun',
	'couscous',
	'farina',
	'farro',
	'flour',
	'pasta',
	'semolina',
	'soy sauce',
	'kimchi paste',
	'spelt flour',
	'rye flour',
	'wheat tortilla',
];
export const NON_VEGANS = ['honey', 'egg'];
export const DAIRIES = [
	'butter',
	'cheese',
	'cottage cheese (tvorog)',
	'crème fraîche',
	'heavy cream',
	'milk',
	'condensed milk',
	'evaporated milk',
	'parmesan cheese',
	'smetana',
	'sour cream',
	'whipping cream',
	'yogurt',
	'milk chocolate',
];
export const ACTUAL_FISHES = ['salmon'];
export const FISHES = [
	...ACTUAL_FISHES,
	'fish sauce',
	'oyster sauce',
	'kimchi paste',
];
export const POULTRIES = [
	'chicken',
	'chicken broth',
	'chicken leg',
	'chicken wing',
	'chicken thigh',
	'chicken breast',
	'chicken chorizo',
];
export const MEATS = [
	'pork',
	'beef',
	'lamb',
	'ham',
	'sausage',
	'bacon',
	'meat',
	'pork chorizo',
];
export const SUGARS = ['sugar', 'dried cranberry', 'marmalade'];

export const GROUPS = {
	Produce: [
		'beetroot',
		'bell pepper',
		'pepper',
		'napa cabbage',
		'red cabbage',
		'savoy cabbage',
		'white cabbage',
		'cabbage',
		'lamb’s lettuce',
		'lettuce',
		'broad bean',
		'green bean',
		'runner bean',
		'sweet corn',
		'corn',
		'scallion',
		'onion',
		'kohlrabi',
		'turnip',
		'cucumber',
		'bok choi',
		'potato',
		'tomato',
		'eggplant',
		'carrot',
		'mangold',
		'chili',
		'pea',
		'pumpkin',
		'squash',
		'zucchini',
		'black radish',
		'radish',
		'chicory',
		'rutabaga',
		'asparagus',
		'mushroom',
		'parsley',
		'rosemary',
		'dill',
		'basil',
		'garlic',
		'parsley root',
		'kale',
		'iceberg salad',
		'salsify',
		'jalapeño',
		'spinach',
		'broccoli',
		'celery',
		'fennel',
		'rucola',
		'cauliflower',
		'parsnip',
		'celeriac',
		'cauliflower',
		'parsnip',
		'brussels sprout',
		'ginger',
		'horseradish',
		'avocado',
	],
	Fruits: [
		'blackcurrant',
		'redcurrant',
		'currant',
		'mandarin',
		'apple',
		'apricot',
		'banana',
		'blueberry',
		'blackberry',
		'gooseberry',
		'cherry',
		'cranberry',
		'grapefruit',
		'lemon',
		'lime',
		'orange',
		'plum',
		'pear',
		'grape',
		'quince',
		'watermelon',
		'raspberry',
		'strawberry',
		'elderberry',
		'fruit',
		'rhubarb',
	],
	Oils: [
		'olive oil',
		'coconut oil',
		'sunflower oil',
		'oil',
		'soy sauce',
		'fish sauce',
		'oyster sauce',
		'vinegar',
		'mustard',
		'olive',
		'caper',
		'tomato paste',
	],
	Legumes: [
		'bean',
		'chickpea',
		'buckwheat',
		'rice',
		'rice noodle',
		'noodle',
		'pasta',
		'couscous',
		'oat',
	],
	DriedFruits: [
		'dried apricot',
		'dried cranberry',
		'nut',
		'peanut',
		'raisin',
		'date',
		'almond',
		'pecan',
	],
	Meat: [...POULTRIES, ...ACTUAL_FISHES, ...MEATS],
	Dairy: [...DAIRIES, 'egg'],
	Baking: [
		'buckwheat flour',
		'teff flour',
		'almond flour',
		'coconut flour',
		'bamboo flour',
		'hazelnut flour',
		'chestnut flour',
		'potato peel flour',
		'flaxseed flour',
		'oat flour',
		'spelt flour',
		'all-purpose flour',
		'flour',
		'corn starch',
		'baking powder',
		'yeast',
		'date sugar',
		'coconut sugar',
		'sugar',
		'maple syrup',
		'chicory syrup',
		'vanilla extract',
		'honey',
	],
	Spices: [
		'salt',
		'black pepper',
		'star anise',
		'bay leaf',
		'rosemary seeds',
		'dried rosemary',
		'cumin seeds',
		'sunflower seeds',
		'sesame seeds',
		'pumpkin seeds',
		'cinnamon',
		'nutmeg',
		'chili flakes',
		'paprika powder',
		'curry powder',
		'curcuma powder',
		'turmeric powder',
		'clove',
		'peppercorn',
	],
};

export const NO_SHOPPING_INGREDIENTS = ['water'];
export const NO_AMOUNTS_GROUPS = ['Oils', 'Spices'];
