export const UNITS = [
	['bag', 'bags'],
	['box', 'boxes'],
	['bunch', 'bunches'],
	['burger', 'burger'],
	['cake', 'cakes'],
	['can', 'cans'],
	['clove', 'cloves'],
	['cup', 'cups', 'c', 'c.'],
	['ft', 'ft', 'foot', 'feet', 'ft.'],
	['g', 'g', 'gram', 'grams', 'g.'],
	['gal', 'gal', 'gallon', 'gallons', 'gal.'],
	['handful', 'handfuls'],
	['head', 'heads'],
	['hot dog', 'hot dogs'],
	['in', 'in', 'inch', 'inches', 'in.'],
	['jar', 'jars'],
	['kg', 'kg', 'kilogram', 'kilograms', 'kg.'],
	['l', 'l', 'liter', 'liters'],
	['layer', 'layers'],
	['lb', 'lbs', 'pound', 'pounds', 'lb.', 'lbs.'],
	['loaf', 'loaves'],
	['mg', 'mg', 'milligram', 'milligrams', 'mg.'],
	['ml', 'ml', 'milliliter', 'milliliters', 'ml.'],
	['oz', 'oz', 'ounce', 'ounces', 'oz.'],
	['package', 'packages', 'pkg', 'pkgs'],
	['piece', 'pieces', 'pcs', 'pcs.'],
	['pinch', 'pinches'],
	['pod', 'pods'],
	['portion', 'portions'],
	['pt', 'pt', 'pint', 'pints', 'pt.'],
	['qt', 'qts', 'quart', 'quarts', 'qt.', 'qts.'],
	['slice', 'slices'],
	['sprig', 'sprigs'],
	['stick', 'sticks'],
	['straw', 'straws'],
	['tablespoon', 'tablespoons', 'tbsp', 'tbsp.'],
	['taco', 'tacos'],
	['teaspoon', 'teaspoons', 'tsp', 'tsp.'],
	['tray', 'trays'],
];

// TODO: Move to language-independent module
export const TEASPOONS_IN_TABLESPOONS = 3;
export const GRAMS_IN_KILOGRAM = 1000;
export const MILLILITERS_IN_LITER = 1000;
