import { defineProperties, createSprinkles } from '@vanilla-extract/sprinkles';
import { conditions, space } from './theme';

const margin = { ...space, auto: 'auto' };

export const responsiveProperties = defineProperties({
	conditions,
	defaultCondition: 'mobile',
	properties: {
		display: [
			'none',
			'flex',
			'grid',
			'block',
			'inline',
			'inline-block',
			'inline-flex',
			'inline-grid',
		],
		flexDirection: ['row', 'column'],
		flexWrap: ['nowrap', 'wrap', 'wrap-reverse'],
		flexShrink: [0],
		alignItems: ['center', 'flex-end', 'flex-start', 'stretch', 'baseline'],
		alignSelf: ['auto', 'baseline', 'normal', 'stretch'],
		justifyContent: [
			'center',
			'flex-end',
			'flex-start',
			'space-around',
			'space-between',
			'stretch',
		],
		justifyItems: ['center', 'flex-end', 'flex-start', 'stretch'],
		columnGap: space,
		rowGap: space,
		padding: space,
		paddingTop: space,
		paddingBottom: space,
		paddingLeft: space,
		paddingRight: space,
		margin,
		marginTop: margin,
		marginBottom: margin,
		marginLeft: margin,
		marginRight: margin,
		//fontWeight: ['normal', 'bold'],
		//fontStyle: ['italic', 'normal'],
		textAlign: ['center', 'end', 'left', 'right', 'start'],
		whiteSpace: ['nowrap'],
		overflow: ['auto', 'clip', 'hidden', 'scroll', 'visible'],
		overflowX: ['auto', 'clip', 'hidden', 'scroll', 'visible'],
		overflowY: ['auto', 'clip', 'hidden', 'scroll', 'visible'],
		verticalAlign: [
			'baseline',
			'bottom',
			'middle',
			'sub',
			'super',
			'text-bottom',
			'text-top',
			'top',
		],
		position: ['absolute', 'fixed', 'relative', 'static', 'sticky'],
		zIndex: [-1],
		width: ['100%'],
		minWidth: ['auto'],
		maxWidth: ['100%'],
	},
	shorthands: {
		gap: ['columnGap', 'rowGap'],
		p: ['padding'],
		paddingInline: ['paddingLeft', 'paddingRight'],
		px: ['paddingLeft', 'paddingRight'],
		paddingBlock: ['paddingTop', 'paddingBottom'],
		py: ['paddingTop', 'paddingBottom'],
		pt: ['paddingTop'],
		pr: ['paddingRight'],
		pb: ['paddingBottom'],
		pl: ['paddingLeft'],
		m: ['margin'],
		marginInline: ['marginLeft', 'marginRight'],
		mx: ['marginLeft', 'marginRight'],
		marginBlock: ['marginTop', 'marginBottom'],
		my: ['marginTop', 'marginBottom'],
		mt: ['marginTop'],
		mr: ['marginRight'],
		mb: ['marginBottom'],
		ml: ['marginLeft'],
		placeItems: ['justifyContent', 'alignItems'],
	},
});

export const atoms = createSprinkles(responsiveProperties);

export type Atoms = Parameters<typeof atoms>[0];
