name: Node.js CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm test
      - run: node --experimental-strip-types scripts/sync-squirrelsong.ts
      - run: npm run build:sapegin
      - run: npm run build:morning
